pull_request_rules:
  - name: Make sure PR are up to date before merging
    description: This automatically updates PRs when they are out-of-date with the
      base branch to avoid semantic conflicts (next step is using a merge
      queue).
    conditions: []
    actions:
      update:
  - name: Close all on main
    conditions:
      - base=main
      - -author~=^dependabot(|-preview)\[bot\]$
    actions:
      close:
        message: Please do not open PR's on the `main` branch, but on the `develop`
          branch only. Thank you!
