"project_id_env": CROWDIN_PROJECT_NR
"api_token_env": CROWDIN_TOKEN

"base_path_env": CROWDIN_BASE_PATH
"preserve_hierarchy": false
files: [
  {
    source: "/resources/lang/en_US/*.php",
    translation: /resources/lang/%locale_with_underscore%/%original_file_name%,

  }
]
